### PR TITLE
fix "Array to string conversion" error

### PR DESCRIPTION
**Pull request by IVoyt**
the commit fixes permanent "Array to string conversion" error

### CODE REVIEW

**Comment by martyf** [comment]
What steps do I need to follow to replicate the issue this is attempting to fix?

**Comment by IVoyt** [comment]
> What steps do I need to follow to replicate the issue this is attempting to fix?

just save any TinyMCE config in Statamic CP. Example config from [the documentation](https://docs.mity.com.au/tinymce-cloud/configuration/tinymce-cloud) should reproduce the error.

The result will be error in ConfigurationDefaults.php
Снимок экрана 2024-06-12 в 11 33 34

**Comment by martyf** [comment]
Righto this is really interesting... on one Statamic 5 site, I do not get the error: but on another I do. 

Your PR fixes one... but for the other no PR is needed. Really odd, so looking in to this now.

**Comment by martyf** [comment]
An update to Statamic's core in 5.7.0 introduced this issue.

I'll merge this PR, and then update it to work with < 5.7 too, and tag it shortly after.

**Comment by IVoyt** [comment]
Ah, sorry, I forgot to note it is Statamic 5.7.x

Thanks!

**Pull request merged**
